Controllers/AccController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GASTOSMVC.Models;

namespace GASTOSMVC.Controllers
{
    public class AccController : Controller
    {
        // GET: Acc
        public ActionResult Index()
        {
            Usuario oUser = new Usuario();
            oUser.nPaso = 0;
            return View(oUser);
        }

        [HttpPost]
        public ActionResult Valida(FormCollection oCollec)
        {
            AccValida oMnVal = new AccValida();
            string WUser = oCollec["txtUsr"].ToString(); string WContra = oCollec["txtContra"].ToString();
            int nValida = oMnVal.Validar(WUser, WContra); oMnVal = null;
            Response.Cookies["IDUsr"].Value = nValida.ToString(); oCollec = null;
            if (nValida == 0)
            {
                Usuario oValida = new Usuario(); oValida.nPaso = 1;
                return View("Index", oValida);
            }
            else
            {
                return RedirectToAction("Index", "ROT");
            }
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GASTOSMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>::: GASTOS.NET :::</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="@Url.Content("~/img/ROCKET.ICO")" />
    <link href="~/Tls/Tls.css" rel="stylesheet" type="text/css" />
    <script src="~/Tls/Tls.js" type="text/javascript"></script>
    <script>
        window.onload = SPLdTblMN;
    </script>
</head>
<body>
    <table id="TblMn" width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td id="TD1" height="92%" valign="top">
                <iframe id="FrmMn" name="FrmMn" src="@Url.Action("Index", "Acc")" frameborder="0" scrolling="auto"></iframe>
            </td>
        </tr>
        <tr>
            <td height="8%" align="center" valign="middle" class="ColorBg">
                <label class="FtoFootI">Derechos Reservados @Html.Raw(DateTime.Now.Year) &copy;</label>
            </td>
        </tr>
    </table>
</body>
</html>